window.DISH_PHOTOS = {
  "BBQ Chicken Wings": "images/dishes/bbq-chicken-wings.jpg",
  "Buttered Garlic Prawns": "images/dishes/buttered-garlic-prawns.jpg",
  "Cheese Balls": "images/dishes/cheese-balls.jpg",
  "Chicken Brunt Garlic Soup": "images/dishes/chicken-brunt-garlic-soup.jpg",
  "Chicken Clear Soup": "images/dishes/chicken-clear-soup.jpg",
  "Chicken Hot 'N' Sour Soup": "images/dishes/chicken-hot-n-sour-soup.jpg",
  "Chicken Lemon Corriender Soup": "images/dishes/chicken-lemon-corriender-soup.jpg",
  "Chicken Loaded Cheese Fries": "images/dishes/chicken-loaded-cheese-fries.jpg",
  "Chicken Lung Fung Soup": "images/dishes/chicken-lung-fung-soup.jpg",
  "Chicken Manchow Soup": "images/dishes/chicken-manchow-soup.jpg",
  "Chicken Pakoda": "images/dishes/chicken-pakoda.jpg",
  "Chicken Pop Corn": "images/dishes/chicken-pop-corn.jpg",
  "Chicken Sweet Corn Soup": "images/dishes/chicken-sweet-corn-soup.jpg",
  "Chicken Thupka Soup": "images/dishes/chicken-thupka-soup.jpg",
  "Chicken Tom Yum Soup": "images/dishes/chicken-tom-yum-soup.jpg",
  "Chicken Wonton Soup": "images/dishes/chicken-wonton-soup.jpg",
  "Cream Of Chicken": "images/dishes/cream-of-chicken.jpg",
  "Cream of Mushroom": "images/dishes/cream-of-mushroom.jpg",
  "Cream Of Spinach": "images/dishes/cream-of-spinach.jpg",
  "Cream Of Tomato": "images/dishes/cream-of-tomato.jpg",
  "Cream Of Veg": "images/dishes/cream-of-veg.jpg",
  "Crispy Chicken Fried Wings": "images/dishes/crispy-chicken-fried-wings.jpg",
  "Crispy Palak Patta Chaat": "images/dishes/crispy-palak-patta-chaat.jpg",
  "Crispy Tikki Chaat": "images/dishes/crispy-tikki-chaat.jpg",
  "Dal Ka Shorba": "images/dishes/dal-ka-shorba.jpg",
  "Fish Pakoda": "images/dishes/fish-pakoda.jpg",
  "French Fries": "images/dishes/french-fries.jpg",
  "Fried Papad": "images/dishes/fried-papad.jpg",
  "Masala Peanuts / Green Peas Fry": "images/dishes/masala-peanuts-green-peas-fry.jpg",
  "Masala Papad": "images/dishes/masala-papad.jpg",
  "Mutton Shorba": "images/dishes/mutton-shorba.jpg",
  "Roasted Papad": "images/dishes/roasted-papad.jpg",
  "Seafood Soup": "images/dishes/seafood-soup.jpg",
  "Tomato Shorba": "images/dishes/tomato-shorba.jpg",
  "Veg Brunt Garlic Soup": "images/dishes/veg-brunt-garlic-soup.jpg",
  "Veg Clear Soup": "images/dishes/veg-clear-soup.jpg",
  "Veg Hot 'N' Sour Soup": "images/dishes/veg-hot-n-sour-soup.jpg",
  "Veg Lemon Corriender Soup": "images/dishes/veg-lemon-corriender-soup.jpg",
  "Veg Lung Fung Soup": "images/dishes/veg-lung-fung-soup.jpg",
  "Veg Manchow Soup": "images/dishes/veg-manchow-soup.jpg",
  "Veg Shorba": "images/dishes/veg-shorba.jpg",
  "Veg Sweet Corn Soup": "images/dishes/veg-sweet-corn-soup.jpg",
  "Veg Thupka Soup": "images/dishes/veg-thupka-soup.jpg",
  "Veg Tom Yum Soup": "images/dishes/veg-tom-yum-soup.jpg",
  "Chicken Shorba": "images/dishes/chicken-shorba.jpg",
  "Garlic Fry": "images/dishes/garlic-fry.jpg",
  "Hara Bhara Kabab": "images/dishes/hara-bhara-kabab.jpg",
  "Paneer Pakoda": "images/dishes/paneer-pakoda.jpg",
  "Kaju Fry": "images/dishes/kaju-fry.jpg",
  "Veg Wonton Soup": "images/dishes/veg-wonton-soup.jpg"
};
